src/Entity/Books.php
<?php

namespace App\Entity;

use App\Repository\BooksRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BooksRepository::class)]
class Books
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?int $Ordre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Auteur = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Titre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Editeur = null;

    #[ORM\Column(nullable: true)]
    private ?bool $Poche = null;

    #[ORM\Column(nullable: true)]
    private ?int $Annee = null;

    #[ORM\Column(nullable: true)]
    private ?int $ISBN = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Distinction = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Collection = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Numero = null;

    #[ORM\Column(nullable: true)]
    private ?int $Tome = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Cycle = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Genre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $SousGenre = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $NoteCath = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $NoteBruno = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Commentaires = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Nationalite = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $TitreOriginal = null;

    #[ORM\Column(nullable: true)]
    private ?int $Date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Emprunteur = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $DateDebut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $DateFin = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Fiche = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $MotsClefs = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrdre(): ?int
    {
        return $this->Ordre;
    }

    public function setOrdre(?int $Ordre): self
    {
        $this->Ordre = $Ordre;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->Auteur;
    }

    public function setAuteur(?string $Auteur): self
    {
        $this->Auteur = $Auteur;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(?string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getEditeur(): ?string
    {
        return $this->Editeur;
    }

    public function setEditeur(?string $Editeur): self
    {
        $this->Editeur = $Editeur;

        return $this;
    }

    public function isPoche(): ?bool
    {
        return $this->Poche;
    }

    public function setPoche(?bool $Poche): self
    {
        $this->Poche = $Poche;

        return $this;
    }

    public function getAnnee(): ?int
    {
        return $this->Annee;
    }

    public function setAnnee(?int $Annee): self
    {
        $this->Annee = $Annee;

        return $this;
    }

    public function getISBN(): ?int
    {
        return $this->ISBN;
    }

    public function setISBN(?int $ISBN): self
    {
        $this->ISBN = $ISBN;

        return $this;
    }

    public function getDistinction(): ?string
    {
        return $this->Distinction;
    }

    public function setDistinction(?string $Distinction): self
    {
        $this->Distinction = $Distinction;

        return $this;
    }

    public function getCollection(): ?string
    {
        return $this->Collection;
    }

    public function setCollection(?string $Collection): self
    {
        $this->Collection = $Collection;

        return $this;
    }

    public function getNumero(): ?string
    {
        return $this->Numero;
    }

    public function setNumero(?string $Numero): self
    {
        $this->Numero = $Numero;

        return $this;
    }

    public function getTome(): ?int
    {
        return $this->Tome;
    }

    public function setTome(?int $Tome): self
    {
        $this->Tome = $Tome;

        return $this;
    }

    public function getCycle(): ?string
    {
        return $this->Cycle;
    }

    public function setCycle(?string $Cycle): self
    {
        $this->Cycle = $Cycle;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->Genre;
    }

    public function setGenre(?string $Genre): self
    {
        $this->Genre = $Genre;

        return $this;
    }

    public function getSousGenre(): ?string
    {
        return $this->SousGenre;
    }

    public function setSousGenre(?string $SousGenre): self
    {
        $this->SousGenre = $SousGenre;

        return $this;
    }

    public function getNoteCath(): ?string
    {
        return $this->NoteCath;
    }

    public function setNoteCath(?string $NoteCath): self
    {
        $this->NoteCath = $NoteCath;

        return $this;
    }

    public function getNoteBruno(): ?string
    {
        return $this->NoteBruno;
    }

    public function setNoteBruno(?string $NoteBruno): self
    {
        $this->NoteBruno = $NoteBruno;

        return $this;
    }

    public function getCommentaires(): ?string
    {
        return $this->Commentaires;
    }

    public function setCommentaires(?string $Commentaires): self
    {
        $this->Commentaires = $Commentaires;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->Nationalite;
    }

    public function setNationalite(?string $Nationalite): self
    {
        $this->Nationalite = $Nationalite;

        return $this;
    }

    public function getTitreOriginal(): ?string
    {
        return $this->TitreOriginal;
    }

    public function setTitreOriginal(?string $TitreOriginal): self
    {
        $this->TitreOriginal = $TitreOriginal;

        return $this;
    }

    public function getDate(): ?int
    {
        return $this->Date;
    }

    public function setDate(?int $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getEmprunteur(): ?string
    {
        return $this->Emprunteur;
    }

    public function setEmprunteur(?string $Emprunteur): self
    {
        $this->Emprunteur = $Emprunteur;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(?\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(?\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }

    public function getFiche(): ?string
    {
        return $this->Fiche;
    }

    public function setFiche(?string $Fiche): self
    {
        $this->Fiche = $Fiche;

        return $this;
    }

    public function getMotsClefs(): ?string
    {
        return $this->MotsClefs;
    }

    public function setMotsClefs(?string $MotsClefs): self
    {
        $this->MotsClefs = $MotsClefs;

        return $this;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Books;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Ordre',IntegerType::class, ['label'=>'Ordre'])
            ->add('Auteur',TextType::class, ['label'=>'Auteur'])
            ->add('Titre',TextType::class, ['label'=>'Titre'])
            ->add('Editeur',TextType::class, ['label'=>'Titre'])
            ->add('Poche')
            ->add('Annee',IntegerType::class, ['label'=>'Année'])
            ->add('ISBN',IntegerType::class, ['label'=>'ISBN'])
            ->add('Distinction',TextType::class, ['label'=>'Distinction'])
            ->add('Collection',TextType::class, ['label'=>'Collection'])
            ->add('Numero',IntegerType::class, ['label'=>'Numéro'])
            ->add('Tome',IntegerType::class, ['label'=>'Tome'])
            ->add('Cycle',TextType::class, ['label'=>'Cycle'])
            ->add('Genre',TextType::class, ['label'=>'Genre'])
            ->add('SousGenre',TextType::class, ['label'=>'Sous-genre'])
            ->add('NoteCath',TextareaType::class, ['label'=>'Notes de Cath'])
            ->add('NoteBruno',TextareaType::class, ['label'=>'Notes de Bruno'])
            ->add('Commentaires',TextareaType::class, ['label'=>'Commentaires'])
            ->add('Nationalite',TextType::class, ['label'=>'Nationalité'])
            ->add('TitreOriginal',TextType::class, ['label'=>'Titre original'])
            ->add('Date',IntegerType::class, ['label'=>'Date'])
            ->add('Emprunteur',TextType::class, ['label'=>'Nom de l\'emprunteur'])
            ->add('DateDebut',DateTimeType::class, ['label'=>'Date de début du prêt'])
            ->add('DateFin',DateTimeType::class, ['label'=>'Date de fin du prêt'])
            ->add('Fiche',TextareaType::class, ['label'=>'Fiche'])
            ->add('MotsClefs',TextareaType::class, ['label'=>'Mots-clés'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Books::class,
        ]);
    }
}

src/Controller/BooksController.php
<?php

namespace App\Controller;

use App\Entity\Books;
use App\Form\BookType;
use App\Repository\BooksRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BooksController extends AbstractController
{
    #[Route('/add/book', name: 'add_book')]
    public function add1(Request $request, EntityManagerInterface $manager): Response
    {
        $book = new Books;
       
        $form = $this->createForm(BookType::class,$book);
        $form->handleRequest($request);
        
            // The form was filled, manage it...
            if($form->isSubmitted() && $form->isValid()) {
                $manager->persist($book); // Persist the first part of your ad object
               $manager->flush();

               $this->addFlash('success','Le livre a bien été ajouté !');

               return $this->redirectToRoute('add_book');
            }


        return $this->render('books/add.html.twig', [
            'controller_name' => 'BooksController',
            'form' => $form
        ]);
    }


    #[Route('/update/book/{id}', name: 'update_book')]
    public function updateBook($id,BooksRepository $repo, EntityManagerInterface $manager, Request $request)
    {
        $book = $repo->find($id);

        $form = $this->createForm(BookType::class,$book);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $book = $form->getData();
            $manager->persist($book);
            $manager->flush();

            $this->addFlash('success','Le livre a bien été modifié !');

            return $this->redirectToRoute('book/edit.html.twig');
        }

        return $this->render('books/edit.html.twig',[
            'form'=>$form,
            'book'=>$book
        ]);

    }

    #[Route('/search', name: 'search_page')]
    public function search(BooksRepository $repo, Request $request)
    {



        return $this->render('books/search.html.twig');

    }
}

templates/books/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BooksController!
{% endblock %}

{% block body %}
	<div class="col-10 offset-1 my-5">
	           {% for label,messages in app.flashes %}

              <div class="container">
                  <div class="alert alert-{{ label }}"> 
                      {% for message in messages %}
                        <p>{{ message | raw }}</p>
                      {% endfor %}
                  </div>
              </div>

            {% endfor %}
		<div class="card border-success col-6 mx-auto">

			<div class="card-body">



				{{ form_start(form)}}
				<h3>Ajouter un livre</h3>

				<div id="formPage1">
					{{ form_row(form.Ordre)}}
					{{ form_row(form.Auteur)}}
					{{ form_row(form.Titre)}}
					{{ form_row(form.Editeur)}}
					{{ form_row(form.Poche)}}
					{{ form_row(form.Annee)}}
					{{ form_row(form.ISBN)}}
					<div class="text-center">
						<button id="suivant" class="btn btn-secondary">Suivant</button>
					</div>
				</div>
				<div id="formPage2" class="d-none">
					{{ form_row(form.Distinction)}}
					{{ form_row(form.Collection)}}
					{{ form_row(form.Numero)}}
					{{ form_row(form.Tome)}}
					{{ form_row(form.Cycle)}}
					{{ form_row(form.Genre)}}
					{{ form_row(form.SousGenre)}}
					{{ form_row(form.NoteCath)}}
					<div class="text-center">
						<button id="suivant2" class="btn btn-secondary">Suivant</button>
					</div>
				</div>
				<div id="formPage3" class="d-none">
					{{ form_row(form.NoteBruno)}}
					{{ form_row(form.Commentaires)}}
					{{ form_row(form.Nationalite)}}
					{{ form_row(form.TitreOriginal)}}
					{{ form_row(form.Date)}}
					<div class="text-center">
						<button id="suivant3" class="btn btn-secondary">Suivant</button>
					</div>
				</div>
				<div id="formPage4" class="d-none">
					{{ form_row(form.Emprunteur)}}
					{{ form_row(form.DateDebut)}}
					{{ form_row(form.DateFin)}}
					{{ form_row(form.Fiche)}}
					{{ form_row(form.MotsClefs)}}

					<div class="text-center">
						<button type="submit" class="btn btn-primary">Ajouter</button>
					</div>
				</div>


				{{ form_end(form)}}
			</div>

		</div>
	</div>
{% endblock %}

{% block javascripts %}
	<script>

		var button = document.getElementById('suivant');

button.addEventListener('click', event => {

document.getElementById("formPage2").classList.add("d-block");
document.getElementById("formPage2").classList.remove("d-none");
document.getElementById("formPage1").classList.add("d-none");
});

var button = document.getElementById('suivant2');

button.addEventListener('click', event => {

document.getElementById("formPage3").classList.add("d-block");
document.getElementById("formPage3").classList.remove("d-none");
document.getElementById("formPage2").classList.add("d-none");
});

var button = document.getElementById('suivant3');

button.addEventListener('click', event => {

document.getElementById("formPage4").classList.add("d-block");
document.getElementById("formPage4").classList.remove("d-none");
document.getElementById("formPage3").classList.add("d-none");
});
	</script>


{% endblock %}

templates/books/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Édition d'un livre
{% endblock %}

{% block body %}

	<div class="col-10 offset-1my-5">
		<div class="card border-success col-6 mx-auto">
			<div class="card-body">
				<h4>Modification de :
				</h4>
				<h3>{{book.titre}}</h3>
				{{ form_start(form)}}
				{{ form_widget(form)}}

				<button type="submit" class="btn btn-primary">Modifier</button>

				{{ form_end(form)}}
			</div>
		</div>
	</div>

{% endblock %}

templates/books/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recherche
{% endblock %}


{% block body %}
	<div class="col-4 offset-4 mt-5">
    <h2 class="text-center">Recherche</h2>
		<form class="text-center">
			<input name="q" class="form-control mt-5 form-lg col-6" type="search">
			<input type="submit" class="btn btn-primary my-3" value="Rechercher">
		</form>
	</div>

{% endblock %}